Fix exit & set sleep time to production value

diff --git a/jinsta_starter b/jinsta_starter
--- a/jinsta_starter
+++ b/jinsta_starter
@@ -1,7 +1,10 @@
 #!/bin/bash
 
+# Make sure no pid is deleted when exiting
+set -e
+
 # Sleep random time between 0 and the time you set
-MAX_SLEEP_SECONDS=10
+MAX_SLEEP_SECONDS=1800
 # Folder where your script is 
 JINSTA_PATH='../jinsta_bot'
 # The command to execute in the above folder
@@ -13,22 +16,22 @@ PIDFILE="${CURRENT_DIRECTORY}/jinsta_starter.pid"
 
 if test -f ${PIDFILE} 
 then 
-    echo "$(date +%F_%H:%M:%S): jinsta already running / error happend. investigate! exiting."| /usr/bin/tee -a ${LOGFILE}
+    echo "$(date +%F_%H:%M:%S) [$$]: jinsta already running / error happend. investigate! exiting."| /usr/bin/tee -a ${LOGFILE}
     exit 1
 else 
     echo $$ > ${PIDFILE}
 fi
 
-echo "$(date +%F_%H:%M:%S): jinsta start script running" | /usr/bin/tee -a ${LOGFILE}
+echo "$(date +%F_%H:%M:%S) [$$]: jinsta start script running" | /usr/bin/tee -a ${LOGFILE}
 
 SLEEP_SECONDS=`expr $RANDOM % $MAX_SLEEP_SECONDS`
-echo "$(date +%F_%H:%M:%S): Sleeping now for $SLEEP_SECONDS" | /usr/bin/tee -a ${LOGFILE}
+echo "$(date +%F_%H:%M:%S) [$$]: Sleeping now for $SLEEP_SECONDS" | /usr/bin/tee -a ${LOGFILE}
 sleep $SLEEP_SECONDS
-echo "$(date +%F_%H:%M:%S): Sleeping is over, let's start jinsta" | /usr/bin/tee -a ${LOGFILE}
+echo "$(date +%F_%H:%M:%S) [$$]: Sleeping is over, let's start jinsta" | /usr/bin/tee -a ${LOGFILE}
 
 cd ${JINSTA_PATH}
 eval ${EXECUTE} | /usr/bin/tee -a ${LOGFILE}
 
-echo "$(date +%F_%H:%M:%S): Runtime was $SECONDS seconds ($(($SECONDS / 60)) minutes)" | /usr/bin/tee -a ${LOGFILE}
+echo "$(date +%F_%H:%M:%S) [$$]: Runtime was $SECONDS seconds ($(($SECONDS / 60)) minutes)" | /usr/bin/tee -a ${LOGFILE}
     
 rm ${PIDFILE}
